- pkg/workflow_execution.go
**What type of PR is this?**
/kind enhancement
Selects the workflow template version createdAt timestamp when listing Workflow Executions.
Fixes onepanelio/core#147
This fix complements the #147 core-ui fix.
> feat: workflow template created at is selected when listing workflow executions

- Dockerfile
- cmd/goose.go
- db/20200525160514_add_jupyter_workspace_template.go
- db/20200528140124_add_cvat_workspace_template.go
- pkg/workspace.go
- pkg/workspace_template.go
What type of PR is this?
/kind enhancement
What this PR does:
This PR adds CVAT as a workspace template to the template builder.
- DB entries and k8s operations are carried out.
This also includes fixes to the JupyterLab migraiton
Which issue(s) this PR fixes:
closes onepanelio/core#317
Special notes for your reviewer:
Make sure you carry out the steps here first:
- https://github.com/onepanelio/manifests/pull/61
- Pull down this branch
- Run `make docker` to push the image to docker
- Update your cluster deployment for onepanel-core to use the commit-hash image
- Wait for changes to take affect
- Exec into your onepanel-core pod
- Run `./goose status` to verify that cvat migration is executed
Note: If you're seeing crash loops, check the onepanel-core logs. The jupyter and cvat …
> feat: add cvat migration template

- server/auth/auth.go
- server/auth_server.go
- server/cron_workflow_server.go
- server/label_server.go
- server/namespace_server.go
- server/secret_server.go
- server/server.go
- server/workflow_server.go
- server/workflow_template_server.go
- server/workspace_server.go
- server/workspace_template_server.go
Refactor and clean up code that gets client from context.
> refactor: clean up client code

- pkg/workspace_template.go
- pkg/workspace_types.go
Allow users to define their own VolumeClaimTemplates.
Fixes onepanelio/core#279
These can be set in Workspace templates as follows:
```
volumeClaimTemplates:
- metadata:
name: data
spec:
accessModes: [ "ReadWriteOnce" ]
storageClass: "my-storage-class"
resources:
requests:
storage: 1Gi
```
If `storageClass` is not set, it defaults to `onepanel`.
If `resource.requests.storage` is set, then no `sys-<name>-volume-size` parameter is generated for the Workspace.
> feat: Allow users to define their own VolumeClaimTemplates

- db/20200421103946_add_back_workflow_template_versions.sql
- db/20200525160514_add_jupyter_workspace_template.go
- db/20200528140124_add_cvat_workspace_template.go
- db/20200605090509_add_pytorch_workflow_template.go
- db/20200605090535_add_tensorflow_workflow_template.go
- db/20200616194847_remove_workflow_template_versions_uid.sql
- pkg/labels.go
- pkg/types.go
- pkg/workflow_template.go
Removes workflow_template_versions uid as it is not needed.
This also fixes an issue where migrations crash because the workflow_template_version.uid is set to a unix timestamp (which has second precision here). The migrations loop over many namespaces and the uid has a unique constraint. When it happens under a second, it crashes.
Fixes onepanelio/core#355
> fix: migrations crash 

- db/20200617122509_remove_url_from_workspaces.sql
- go.sum
- main.go
- pkg/config.go
- pkg/workflow_execution.go
- pkg/workspace.go
- pkg/workspace_template.go
- pkg/workspace_template_types.go
- pkg/workspace_types.go
- server/workflow_server.go
- server/workspace_server.go
Updates the workspace templates so that runtime variables like the DOMAIN are injected when the workspace is is created instead of when the workspace template is created.
This also updates the server so that it reloads data upon a detected configuration change, so variables like DOMAIN are always up to date.
Fixes onepanelio/core#348
For the runtime variables, there are 3 main places of interest.
- When we create a template for viewing, as when we generate a dynamic template while creating/editing a workspace template. In this situation, we need to inject runtime variables for things like the Machine Type dropdown.
- Whenever we get a Workspace Template, we need to modify the manifest to include …
> feat: runtime variables and system config change reload

- db/go/20200525160514_add_jupyter_workspace_template.go
- db/go/20200528140124_add_cvat_workspace_template.go
- db/go/20200605090509_add_pytorch_workflow_template.go
- db/go/20200605090535_add_tensorflow_workflow_template.go
- db/go/20200626113635_update_cvat_workspace_template.go
- db/go/20200704151301_update_cvat_workspace_template.go
- db/go/db.go
- pkg/config_types.go
- server/workspace_server.go
Fixes an issue where get workspaces did not return up to date node pool options.
This is seen in the UI in the workspace details view page - in the node pool options in the bottom panel.
Fixes onepanelio/core#407
To test 
1. Start a workspace (any is good)
2. Wait until it is running
3. Go to the detail page, and open the bottom panel. Check the node pool options.
4. Edit your onepanel configmap node pool options and add an option (or remove)
5. Refresh the page and check the node pool options.
> fix: get workspaces now returns up-to-date node pool options

- main.go
- server/auth/auth.go
- server/workspace_server.go
* Adds support for `onepanel-auth-token` to be a header that provided authentication
* Updates the server's header parsing to not require grpc-gateway for certain headers of our choosing.
* Add reserved workspace names
> feat: onepanel-auth-token header for authentication

- pkg/config_types.go
configmap, if they are not filled.
- Adding explicit yaml conversion for serviceAccountJSON, otherwise
"omitempty" shows in the configmap.
> fix: Adding omitempty to prevent the keys from showing up in onepanel

- api/api.swagger.json
- pkg/common_types.go
- pkg/cron_workflow_types.go
- pkg/cron_workflow_types_test.go
- server/converter/converter.go
- server/workflow_template_server.go
Refactors parameter parsing for cron workflows from their manifest to use yaml unmarshaling, which is safer and cleaner.
Fixes onepanelio/core#450
> chore: simplify logic for parsing parameters from cron workflow manifests

- api/api.proto
- api/api.swagger.json
- main.go
Increases the server and client message size.
- Both receive and sending.
Fixes onepanelio/core#414
To test, create a workflow that outputs a main.log file of over 10 MB.
Then try downloading it.
You should be able to download the file and not get any console errors in the browser.
> fix: issue where downloading artifact files from a workflow over 10 MB failed

- pkg/workspace_template.go
Fix issue where workspaceTemplate namespace was not set before setting service environment variables
These were called from migrations
> fix: issue with migrations failing to run

- pkg/workflow_execution.go
- pkg/workflow_template.go
Fixes an issue where API did not return a useful error message when the workflow template name was too long (when creating or cloning).
Fixes onepanelio/core#458
> fix: add more useful error message when workflow template name is too long

- pkg/workspace_template.go
Fixes an issue where volume size parameter was added for `sys-namespace-config` volume mount. The end user should not have the option to set a volume size for system volumes.
To test, add the `sys-namespace-config` volume to a container as follows and check that a volume size parameter is not added:
```yaml
- name: filesyncer
image: onepanel/filesyncer:s3
...
volumeMounts:
- name: sys-namespace-config
mountPath: /etc/onepanel
readOnly: true
...
```
> fix: Skip generation volume size parameters for system volumes

- pkg/common_types.go
Makes parameter visibility default to public.
Fixes onepanelio/core#511
> feat: make default visibility public for parameters

- pkg/workflow_execution.go
- Otherwise, the workflow can't get access to GCS bucket.
Fixes onepanelio/core#547
> fix: Updating code that injects the location of the serviceAccountToken if Google Cloud Storage is used.

- pkg/workflow_template.go
Fixes an issue where the labels applied at the workflow template creation did not persist if you updated the workflow template later.
Fixes onepanelio/core#601
> fix: workflow template labels persistence

- pkg/workflow_execution.go
- pkg/workspace.go
This should fix Workspaces not starting because the "cpu" and "memory" request values are "".
- k8s throws a "cannot parse error"
If the node is not running, then we don't try to allocate the resource limits / requests.
**Checklist**
Required
> fix: Do not try to calculate resource requests and limits if the node is not running.

- server/auth/auth.go
Fixes issue where null token sent in breaks the jwt token.
Fixes onepanelio/core#653
**Checklist**
Required
> fix: bad token issue

- pkg/client.go
- server/auth/auth.go
Use a system-wide db connection for the auth check.
**Checklist**
Required
> fix: use system-wide db connection for auth

- .github/workflows/push_tag.yaml
Changes the slack channel notified of new build tags to be 'org' instead of 'dev'.
**Checklist**
Required
> fix: change notify slack channel to be org instead of dev

- db/data/cvat_20201016170415.yaml
Fixes an issue where latest cvat migration had a hard-coded filesyncer.
**Checklist**
Required
> fix: non-generic filesyncer for latest cvat migration

- pkg/client.go
- pkg/config_types.go
- server/auth/auth.go
- server/auth_server.go
Moves token to be inside client instead of sysconfig as it is not a system config value, but it is applicable to the current client.
This fixes some concurrency issues since you could have multiple requests handled at the same time that try to read and modify the system values.
**Checklist**
Required
> fix: concurrency issues with token

- pkg/labels.go
Fixes issue where terminated workspace labels were being selected
Fixes onepanelio/core#701
**Checklist**
Required
> fix: issue where terminated workspace labels were being selected

- go.mod
- go.sum
- pkg/workflow_execution.go
- Specifically, if a sidecar is labeled with "sys-tensorboard-like",
code attempts to create services and virtual services (routes).
- Code will create argo templates that are resource type, where the
manifests are the generated resources.
The templates are then added right before the template with the
sidecar that requires these services and routes.
**Checklist**
Required
> feat: Add support for visualization sidecars

- go.mod
- go.sum
- pkg/workflow_execution.go
- server/workflow_server.go
Using Argo stop command instead of terminate allows the Workflow to still execute exitHandler tasks.
**Checklist**
Required
> feat: Terminate Workflow action will still execute exitHandler tasks

- pkg/client.go
- pkg/util/env/env.go
Update kubernetes timeout to be set via environment variable
**Checklist**
Required
> feat: update kubernetes timeout to be set via environment variable

- pkg/workflow_execution.go
- pkg/workspace.go
Support `nvidia.com/gpu=present:NoSchedule` node taint in GKE
Fixes onepanelio/core#772
**Checklist**
Required
> feat: Support GPU resource limits in Workspaces and Workflows

- pkg/workflow_execution.go
Adjusts curl so a specific version is used. Changes the functionality so all errors, even 4xx ones are retried, and if a non 2xx response is returned, cause the container to error out instead of continuing successfully. Also increased retries in case of longer network errors. 
**Checklist**
Required
> fix: adjust curl to use specific version and fail on non 200 responses

- db/yaml/jupyterlab/20201214133458.yaml
This fixes an issue where JupyterLab terminal would not open in the `/data` directory.
**Checklist**
Required
> fix: Set jupyterlab workingDir to /data

- db/go/20201214133458_fix_jupyterlab_gpu.go
- main.go
- pkg/client.go
- pkg/workflow_execution.go
Fixes various issues in core
1. Issue where websockets for watching workflow executions would close because of k8s timeouts that were not handled
2. migration had missing initialization variable. This caused a crash when configmap changed.
3. Update configmap watcher to have it's own kube client that has no timeout as configmap watching has lots of timeouts, even on 3 minutes.
Fixes onepanelio/core#798
**Checklist**
Required
> fix: closing web sockets

- db/yaml/workflows/tf-object-detection-training/20201223202929.yaml
> fix: Rename train.py => main.py in TFOD workflow template

- pkg/workflow_execution.go
Fixes onepanelio/core#828
**Checklist**
Required
> feat: replace parameter namespace values with runtime value

- pkg/workflow_execution.go
> feat: add {{workspace.uid}} to parameters as a replaceable value

- db/yaml/workflows/hyperparameter-tuning/20210118175809.yaml
> chore: Update hyperparameter tuning template

- main.go
> fix: move db migrations outside of configmap changes

- pkg/util/collection/collection.go
- pkg/workflow_execution.go
- server/workflow_server.go
> feat: filesyncer sidecar for workflows

- pkg/workflow_execution.go
- pkg/workspace.go
> feat: updated workflow/workspace fields to allow some related field queries
