main.go

Added patch to allowed methods

---

server/workflow_server.go

fix: issue where logs were sending duplicate data.

---

pkg/workflow_execution.go
server/workflow_server.go

closes https://github.com/onepanelio/core/issues/95

Returning a 404 if no metrics are found.

---

pkg/workflow_execution.go

closes #https://github.com/onepanelio/core/issues/109

Feature/core.109 sys.env.vars

---

pkg/workflow_execution.go

closes https://github.com/onepanelio/core/issues/149

Injecting ONEPANEL_HOST to workflows.

---

pkg/client.go
pkg/types.go

closes https://github.com/onepanelio/core/issues/158

Feat/core.158 move.s3.config

---

pkg/workflow_execution.go

closes https://github.com/onepanelio/core/issues/160

Feat/core.160 add.url.update.host

---

pkg/client.go
pkg/util/env/env.go
pkg/workflow_execution.go
pkg/workspace_template.go

- Mount environment variables in Workspaces
- Use `EnvFrom` in Workflows as well
- Fix `ArtifactRepository` const names

Mount environment variables

---

pkg/client.go
pkg/config_types.go
pkg/workflow_execution.go

feat: inject default artifact repository for input/output artifacts without creds defined

---

api/api.swagger.json
api/workflow.pb.go
api/workflow.pb.gw.go
api/workflow.proto
pkg/config.go
pkg/types.go
pkg/workflow_execution.go
pkg/workspace_template_types.go
pkg/workspace_types.go
server/workflow_server.go

feat: ns scoped artifact config

---

api/api.swagger.json
api/workflow.pb.go
api/workflow.pb.gw.go
api/workflow.proto
pkg/types.go
pkg/workflow_execution.go
pkg/workspace_template_types.go
pkg/workspace_types.go
server/workflow_server.go

Addresses issue described in https://github.com/onepanelio/core-ui/pull/70#issuecomment-630482451
closes #222

feat: workflow status update hook

---

pkg/common_types.go
pkg/workflow_execution.go

Fix/onepanelio.core.234 workflow.details.issues

---

pkg/cron_workflow.go
pkg/workflow_template.go

- Code will clean up any WorkflowExecutions, including those in progress.
Code then cleans up the scheduled cron workflow, archiving it in the database.

Fixed TerminateCronWorkflow

---

pkg/workflow_template.go

- Iterate through each version and grab the related WorkflowExecutions,
then archive them.
closes https://github.com/onepanelio/core/issues/254
Create template, named "dag"
Create 2 workflow execs, a cron
Edit template, "dag"
Save, so there are two versions
Create 2 workflow execs, a cron
Wait for cron to create at least 1
Delete / Archive the workflow template
Create template named "dag"
- You should see no entries, for workflows or crons

fix: update archive code to list all the template versions.

---

pkg/config_types.go
pkg/workflow_execution.go

closes onepanelio/core#282 (along with manifests PR)

update: hard-coded artifacts key format with the new config.

---

server/converter/converter.go

Fix/onepanelio.core.304 labels.listing.order

---

pkg/workspace_template.go

fix: workspace update waits for correct success condition

---

scripts/README.md
scripts/generate-release-md.go

**What type of PR is this?**
/kind docs
Provides a script for generating release mark down which includes changelog and contributors list.
None
See [scripts/README.md](https://github.com/onepanelio/core/blob/1c085d8794446b4929b23196b78f010980769acc/scripts/README.md) for information on how to run this script

chore: generate release MD script

---

pkg/workspace_template.go

**What type of PR is this?**
/kind bug
Fixes a compile error. The function name was refactored but not in the rest of the code.
Fixes #
Try to compile, it should work.

fix: Fixing function name.

---

db/20200525160514_add_jupyter_workspace_template.go
db/20200528140124_add_cvat_workspace_template.go

Fixes the YAML indentation in `slack-notify` so once comments are removed, the YAML and preview render correctly.
When you edit any of these Workflow Templates and uncomment the `postExecutionWorkflow` section, the graph preview on the right hand side should update accordingly.

fix: Slack notify YAML indentation

---

cmd/README.md
cmd/gen-release-md.go
scripts/README.md

Updates `gen-release-md.go` and README for commands.
N/A

chore: update gen-release-md command and README

---

db/20200605090509_add_pytorch_mnist_workflow_template.go
db/20200605090509_add_pytorch_workflow_template.go
db/20200605090535_add_tensorflow_workflow_template.go

Adds Pytorch and Tensorflow as Workflow Templates to all users.
Fixes onepanelio/core#https://github.com/onepanelio/core/issues/288
Deploy this to your cluster.
- Either through image or local development
- You should see templates in workflows page

feat: Adding Pytorch and Tensorflow to workflow templates, as runnable workflow executions.

---

cmd/README.md
cmd/gen-release-md/gen-release-md.go

Updates `gen-release-md` command to include information for Windows install + get the correct milestone per repository based on milestone title.

chore: update release command 

---

pkg/workspace_template.go

This addressed this issue https://github.com/kubernetes/kubernetes/issues/28272.

fix: Shared memory in Workspaces

---

pkg/workspace_template.go

Allows users to reference parameters in Workspace Templates like so:
```yaml
‘{{workspace.parameters.param-name}}’
```

fix: reference to parameters can now be defined as `workspace.parameters`

---

pkg/workspace_template.go
server/auth/auth.go
server/workspace_server.go

- Create a `Workspace` K8s resource when a Workspace is created.
- Check auth against `Workspace` resource
Fixes onepanelio/core#360
This PR does not add the appropriate Kubernetes structs. This should be done in a subsequent phase.

feat: Authorize against Workspace CRD

---

pkg/util/error.go
pkg/workspace_template.go

- Fixes the Workspace Template parameter validation message
- Introduces a new error type due to https://github.com/grpc/grpc-go/issues/2934
Fixes onepanelio/core#366

fix:  workspace template message

---

pkg/util/error.go
pkg/workspace_test.go
pkg/workspace_types.go

This ensures gRPC errors return the correct status code

fix: return correct gRPC code

---

db/20200626113635_update_cvat_workspace_template.go
pkg/workspace_template.go
server/workspace_template_server.go

Updates default cvat template
Fixes onepanelio/core#376

feat: cvat template

---

db/20200626113635_update_cvat_workspace_template.go
db/20200704151301_update_cvat_workspace_template.go

Comment out filesyncer and reference docs in CVAT Workspace Template

fix: Comment out filesyncer to avoid CVAT template crashing

---

db/20200704151301_update_cvat_workspace_template.go

Comment out filesyncer and reference docs in CVAT Workspace Template

fix: Update CVAT template to Comment out filesyncer to avoid crashing

---

cmd/goose/goose.go
main.go

Fixes an issue with goose binary.

fix: goose binary errors

---

pkg/config_types.go

to properly unmarshal nodePoolOptions from params.yaml.

fix: Regression fix; We need the specific sigs.k8s.io/yaml library

---

pkg/config_types.go

fix: Use consistent naming convention for GCS artifactRepository secret key

---

db/go/20200724220450_update_cvat_workspace.go
db/go/db.go
pkg/workspace_template.go

feat: Mount namespace config for system containers

---

api/cron_workflow.pb.gw.go
api/namespace.pb.gw.go
api/workflow.pb.gw.go
api/workflow_template.pb.gw.go
api/workspace.pb.gw.go
api/workspace_template.pb.gw.go

Updates the API autogenerated code.

chore: update api docs

---

cmd/goose/goose.go
db/go/20200525160514_add_jupyter_workspace_template.go
db/go/20200528140124_add_cvat_workspace_template.go
db/go/20200605090509_add_pytorch_workflow_template.go
db/go/20200605090535_add_tensorflow_workflow_template.go
db/go/20200626113635_update_cvat_workspace_template.go
db/go/20200704151301_update_cvat_workspace_template.go
db/go/20200724220450_update_cvat_workspace.go
db/go/20200727144157_add_parameters_to_workflow_template_version.go
db/go/20200728190804_update_workflow_template_labels.go
db/go/db.go
main.go
pkg/common_types.go
pkg/common_types_test.go
pkg/workflow_execution.go
server/workflow_template_server.go

Fixes db connection leaks.
Fixes onepanelio/core#446, onepanelio/core#449

fix: database connection leak

---

api/api.swagger.json
pkg/common_types.go
server/converter/converter.go
server/workflow_template_server.go

Adds an API check to make sure parameters are one of four values
* public
* protected
* internal
* private
Also adds a minor clean up to parameter conversion from v1 to api. This conversion uses the method from the conversion package, which has had a slight change to add visibility.
Fixes onepanelio/core#440

fix: restricted parameter visibility to not allow any random value

---

pkg/util/error.go
pkg/workflow_template.go

fix: workflow template visibility gave incorrect error

---

pkg/workflow_execution.go

Fixes issue where running a workflow execution again failed.
Fixes onepanelio/core#473

fix: issue where running a workflow execution again failed

---

pkg/workspace_template.go
server/workspace_template_server.go

Adds service urls to the auto-mounted environment variables.
Fixes onepanelio/core#476

feat: added service environment variables to be mounted into workspaces

---

pkg/common_types.go

fix: issue where parameter display name was not being parsed correctly

---

pkg/workflow_execution.go

Fixes an issue where long lines prevented loading of logs.
Fixes onepanelio/core#489

fix: issue where log didn't render long lines

---

db/go/20200728190804_update_workflow_template_labels.go
db/sql/20200807161614_upgrade_labels_to_jsonb.sql
pkg/cron_workflow.go
pkg/cron_workflow_types.go
pkg/label_types.go
pkg/labels.go
pkg/util/label/label.go
pkg/util/types/types.go
pkg/workflow_execution.go
pkg/workflow_execution_types.go
pkg/workflow_template.go
pkg/workflow_template_types.go
pkg/workflow_template_version_types.go
pkg/workspace.go
pkg/workspace_template.go
pkg/workspace_template_types.go
pkg/workspace_types.go
server/workflow_server.go
server/workflow_template_server.go

Upgrades labels to be stored in each table in a JSONB column.
Migrates old labels to the new label structure.
Upgrades workflow template label filter to support ANDing with multiple labels.
Fixes onepanelio/core#467

feat: upgrade label structure to support querying with multiple labels

---

pkg/workflow_template.go

Fixes a bug where selecting workflow templates by a labels query fails.

fix: bug with counting workflow templates with labels query

---

pkg/workflow_execution.go

Removes the `nvidia-smi` mount.
Fixes onepanelio/core#485
Here's a Workflow that can be run to validate this:
```yaml
arguments:
parameters:
- name: command
value: 'nvidia-smi'
- name: sys-node-pool
value: Standard_NC6
entrypoint: main
templates:
- dag:
tasks:
- name: train-model
template: tensorflow
name: main
- name: tensorflow
nodeSelector:
beta.kubernetes.io/instance-type: '{{workflow.parameters.sys-node-pool}}'
container:
args:
- '{{workflow.parameters.command}}'
command:
- sh
- -c
image: tensorflow/tensorflow:1.13.1-gpu-py3
```

chore: Remove nvidia-smi mount

---

pkg/workflow_execution.go

Allows support for [Script](https://github.com/argoproj/argo/tree/master/examples#scripts--results) templates for Workflows.
Fixes onepanelio/core#503

feat: Support script templates in Workflow

---

pkg/workspace.go

Fixes an issue where creating a workspace with no matching template caused a panic
Fixes onepanelio/core#505

fix: issue where creating a workspace with no matching template caused a panic

---

server/auth/auth.go

Fixes issue where auth would sometimes crash
Fixes onepanelio/core#509

fix: issue where auth would sometimes crash

---

api/api.swagger.json
db/go/20200812104328_update_maskrcnn_and_tf_od.go
db/go/20200812113316_update_cvat.go
db/go/db.go
server/auth/auth.go

feat: Update migrations for maskRCNN, tf od, and cvat 

---

db/go/20200812104328_update_maskrcnn_and_tf_od.go
db/go/20200812113316_update_cvat.go
db/go/20200814160856_add_description_to_jupyter_template.go
db/go/db.go

fix: migrations to include latest cvat image and descriptions

---

db/go/20200812104328_update_maskrcnn_and_tf_od.go

fix: issue with migration for creating maskrcnn

---

db/go/20200812104328_update_maskrcnn_and_tf_od.go

- Fixes the incorrect TFOD template that was causing a sh error
- Makes certain TFOD template parameters private
- Updates the TFOD template name

fix: Update TFOD migration

---

pkg/workflow_execution.go
server/workspace_server.go

Fixes static ip in curl commands for workspaces
Fixes onepanelio/core#522

fix: update core pod host to use name instead of static value

---

server/workspace_server.go

fix: extra import

---

db/go/20200812104328_update_maskrcnn_and_tf_od.go

Update TF object detection workflow name to be less than 30 characters.

fix: Update TF object detection workflow name

---

db/go/20200812104328_update_maskrcnn_and_tf_od.go

Fix issue where a non-exiting workflow template attempted to create a workflow template version.
Fixes onepanelio/core#529

fix: issue where migration crashed

---

db/go/20200812104328_update_maskrcnn_and_tf_od.go
db/go/20200824095513_update_mask_rcnn.go
db/go/20200824101019_update_tf_object_detection_training.go
db/go/20200824101905_update_cvat_template.go
db/go/db.go

Updates migrations for cvat, tf object detection training, mask rcnn

feat: updated migrations for cvat, tf od training, maskrcnn

---

db/go/20200626113635_update_cvat_workspace_template.go
db/go/20200704151301_update_cvat_workspace_template.go
db/go/20200724220450_update_cvat_workspace.go
db/go/20200812113316_update_cvat.go
db/go/20200824101905_update_cvat_template.go

Fixes issue where migrations crashed with multiple namespaces

fix: issue where migrations crashed with multiple namespaces

---

db/go/20200812104328_update_maskrcnn_and_tf_od.go
db/go/20200824095513_update_mask_rcnn.go
db/go/20200824101019_update_tf_object_detection_training.go
db/go/20200824101905_update_cvat_template.go
db/go/db.go

- Updating various migrations
- Adding helper function

fix: Adding support for different bucket storages in the db migrations

---

db/go/20200824101905_update_cvat_template.go

fix: Fixing code that was removed during a merge and caused a regression.

---

db/go/20200825154403_update_cvat_version.go
db/go/db.go

Update cvat workspace template to 0.12.0_cvat.1.0.0

fix: cvat to 0.12.0_cvat.1.0.0

---

db/go/20200821162630_update_jupyter_workspace_template.go
db/go/db.go

Adds migration for new Jupyterlab Workspace.
Fixes onepanelio/core#415

feat: Added migration for new Jupyterlab Workspace, 1.0.1

---

db/go/20200826185926_upgrade_cvat.go
db/go/db.go

feat: upgraded cvat template with new filesyncer changes

---

.github/workflows/bump_version_minor.yaml
.github/workflows/push_dev_branch.yaml
.github/workflows/run_unit_tests.yaml

Revert "fix: changed workflows since master branch is now development"

---

.github/workflows/push_dev_branch.yaml

fix: for master push, release a new dev image only

---

README.md

docs: Update build status badge

---

README.md

Revert FAQ change

---

README.md

docs: Additional quick start videos

---

db/go/20200922103448_add_jupyter_lab_description.go
db/go/db.go

Adds a description to the workspace template for jupyterlab
Fixes onepanelio/core#599

feat: add description to jupyterlab workspace template

---

pkg/workflow_template.go

Fix an issue where some workflow templates like PyTorch and TensorFlow don't show up anymore.
Fixes onepanelio/core#613

fix: issue where some workflow templates don't show up

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the PR template to include a checklist to remind people to do unit tests, documentation, and the license of the project.
Fixes onepanelio/core#597

feat: pull request template updates

---

db/go/20200821162630_update_jupyter_workspace_template.go
db/go/20200929153931_update_jupyter_lab_workspace_command.go
db/go/db.go

Adds `onepanel-sdk` to jupyterlab workspace.
**Checklist**
Required

feat: Adding migration to update jupyterlab workspace to include `onepanel-sdk`

---

db/go/20200929144301_add_vscode_workspace_template.go
db/go/db.go

Adds VSCode workspace template to workspaces, via migration.
Fixes onepanelio/core#609
PR https://github.com/onepanelio/templates/pull/37 should be merged first.
**Checklist**
Required

feat: Adding migration for VSCode to be added as a workspace template.

---

db/go/20200929144301_add_vscode_workspace_template.go

Updates the name and description of vscode template so it fits in the ui
**Checklist**
Required

chore: update name and description for vscode template so it fits in ui

---

pkg/util/request/request.go
pkg/workflow_execution.go
pkg/workflow_template.go
pkg/workspace.go
pkg/workspace_template.go

Fixes unit tests
**Checklist**
Required

fix: unit tests

---

db/go/20201001070806_update_cvat.go
db/go/db.go

Updates cvat workspace template
**Checklist**
Required

feat: update cvat workspace template

---

db/go/20200821162630_update_jupyter_workspace_template.go
db/go/20200929153931_update_jupyter_lab_workspace_command.go

Fixes issue where more than one namespace causes migration issues.
**Checklist**
Required

fix: issue where more than one namespace caused migration issues

---

.github/workflows/push_tag.yaml

fix: build docker image on tag push

---

cmd/gen-release-md/gen-release-md.go

Removes dependabot[bot] from release notes generation
Fixes onepanelio/core#631
**Checklist**
Required

fix: remove dependabot[bot] from release notes

---

pkg/workspace.go

Adds resource requirements logic to start workspace method.
**Checklist**
Required

fix: added resource requirements to start workspace

---

pkg/workflow_execution.go
pkg/workspace.go

Per Rush's discovery, we can use hostPort to request a dedicated node from k8s.
- This also works for scaling from 0 nodes
This PR replaces requests logic with adding a hostPort via an extra container.
Fixes onepanelio/core#637
**Checklist**
Required

fix: Replace resource requests and limits with hostPort, as a means of grabbing dedicated nodes.

---

pkg/workflow_execution.go
pkg/workspace.go

Fixes onepanelio/core#637
**Checklist**
Required

fix: Fixing issues with using hostPort. Removed prior logic that still relied on running nodes.

---

db/go/20200929153931_update_jupyter_lab_workspace_command.go
pkg/workspace_template.go

Fixes onepanelio/core#641
**Checklist**
Required

feat: added convenience method to update workspace template manifest

---

server/workspace_server.go

Fixes the incorrect group used for workspaces resource
**Checklist**
Required

fix: Use correct group for workspaces resource

---

server/auth/auth.go

Fixes an issue with concurrent map access
Fixes onepanelio/core#653
**Checklist**
Required

fix: issue with concurrent map access

---

server/label_server.go

Update label function to return group and resource
**Checklist**
Required

fix: Update label function to return group and resource

---

server/auth/auth.go

Fixes an issue where db connection does not close.
**Checklist**
Required

fix: close db connection when not in use.

---

pkg/workspace_template.go

Use `sys-uid` instead of `sys-name` for `ONEPANEL_RESOURCE_UID`
**Checklist**
Required

fix: Use sys-uid instead of sys-name for ONEPANEL_RESOURCE_UID

---

pkg/workflow_execution.go

Fixes issue where listing files with gcs were not working.
**Checklist**
Required

fix: issue where files were not being listed when using gcs

---

db/data/cvat9.yaml
db/go/20201016170415_update_cvat.go
db/go/db.go
db/go/util.go

Updates cvat workspace template
**Checklist**
Required

feat: update cvat

---

README.md

Update support badge
**Checklist**
Required

docs: Update support badge

---

db/data/20201102104048_cvat.yaml

fix: Fixing typo in CVAT migration yaml.

---

db/go/20201102104048_update_cvat_reduce_vols.go
db/go/db.go

Fixes an issue where a new migration wasn't set up properly, causing it to run before all other migrations.
**Checklist**
Required

fix: issue where new migration ran before all others, causing issues

---

pkg/workflow_execution.go

Fixes issue where workflow breaks if there are multiple starting tasks in it
Fixes onepanelio/core#667
**Checklist**
Required

fix: Only inject one sys-send-status task

---

pkg/workflow_execution.go

- Not used
- We're using a different function
**Checklist**
Required

chore: Removing ensureWorkflowRunsOnDedicatedNode function.

---

db/data/20201113094916_cvat.yaml
db/go/20201113094916_update_cvat_onepanel_sdk.go
db/go/db.go

- This image updates the authentication endpoint used for Onepanel
user credentials, inside of CVAT.
Test with image: `9ddd69b`
**Checklist**
Required

chore: Adding migration for new CVAT image.

---

pkg/labels.go

fix: issue where workspace label selection wasn't working.

---

db/sql/20201118200215_fix_default_migration.sql

fix: issue where previous metrics migration was using incorrect format

---

Dockerfile

build: Bring Go to 1.15.5 in Dockerfile

---

README.md

Added link to http://landscape.lfai.foundation/selected=onepanel
**Checklist**
Required

feat: include LF AI Landscape onepanel link

---

.github/workflows/push_tag.yaml

Github has updated environment variables handling and our builds are now failing. This fixes it.
Fixes onepanelio/core#743
**Checklist**
Required

fix: github actions 

---

pkg/workspace.go
pkg/workspace_template.go

fix: Move env vars to workspace creation

---

pkg/client.go

fix: added timeout to k8s so it doesn't wait forever.

---

db/go/20201031165106_add_tensorboard_env_var_to_jupyterlab_template.go

fix: wrong migration folder

---

db/go/20201209124226_update_tensorflow_training.go
db/go/db.go
db/yaml/tf_training/20200605090535.yaml
db/yaml/tf_training/20201209124226.yaml

feat: update tensorflow migration

---

db/yaml/tf_training/20201209124226.yaml

fix: tf training with epochs

---

pkg/workflow_execution.go

Fixes onepanelio/core#772
**Checklist**
Required

fix: Correctly add resources to script templates

---

pkg/workspace.go

Fixes onepanelio/core#780
**Checklist**
Required

fix: issue where workspace params were not updated

---

pkg/workspace.go

chore: changed variable name to better reflect purpose

---

db/go/20201211161117_fix_resources_gke.go
db/go/db.go
db/yaml/cvat/20201211161117.yaml
pkg/workspace.go

fix: GPU not being present in GKE for workspaces

---

db/go/20201214133458_fix_jupyterlab_gpu.go
db/go/db.go
db/yaml/jupyterlab/20201214133458.yaml

fix: Issue where gpu didn't work for jupyterlab in gke

---

README.md

chore: Update demo note

---

pkg/workflow_execution.go

Resolves the intermittent patch issue with Workflows with sidecars.
**Checklist**
Required

fix: Resolves intermittent errors in Workflows with Sidecars

---

db/go/20201225172926_add_hyperparameter_tuning_example_workflow_template.go

fix: Path to hyperparameter-tuning migration

---

db/go/20201225172926_add_hyperparameter_tuning_example_workflow_template.go

fix: Use correct label for hyperparameter tuning Workflow

---

cmd/gen-release-md/gen-release-md.go

feat: improve error message for not found milestones

---

Makefile

feat: make api command use docker by default.

---

pkg/workflow_execution.go
server/workflow_server.go

fix: issues with finished logs

---

pkg/types.go
pkg/workflow_execution.go

fix: issue where logs would sometimes crash

---

db/yaml/workflows/hyperparameter-tuning/20201225172926.yaml
db/yaml/workflows/pytorch-mnist-training/20201221194344.yaml
db/yaml/workflows/tensorflow-mnist-training/20201223062947.yaml

chore: Remove archive from templates

---

db/go/20201223062947_tf_training_update_node_pool.go

fix: Remove used-by: cvat from tf training workflow

---

pkg/workspace_template.go
pkg/workspace_types.go

You can use a private docker registry for images.
Fixes onepanelio/core#804
You will need a private docker repository to test this change.
You can use this one: https://portal.azure.com/#@azure.onepanel.io/resource/subscriptions/36388866-b2b1-41a5-80e2-da43baebfe67/resourceGroups/dev/providers/Microsoft.ContainerRegistry/registries/alexnuclio/overview
- Ask me for credentials
You can also set one up in Azure, following these instructions
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-azure-cli
You'll eventually get credentials for this repository.
```
{
"appId": "<this is the username for docker login>", #username
"displayName": "mynuclioacr-sp",
"name": …
```

feat: Adding support for ImagePullSecrets in workspaces and workflows

---

db/go/20210107094725_update_cvat_workspace.go
db/go/db.go
db/yaml/workspaces/cvat/20210107094725.yaml

Updates CVAT and FileSyncer images. Relevant PRs:
https://github.com/onepanelio/templates/pull/55
https://github.com/onepanelio/cvat/pull/35
Fixes onepanelio/core#795
**Checklist**
Required

feat: Update CVAT and FileSyncer images

---

pkg/workflow_execution.go
pkg/workflow_template.go
pkg/workflow_template_version_types.go

feat: add parameters to workflow template versions response

---

pkg/workflow_execution.go

fix: Only remove whitespaces in var references

---

.github/workflows/push_dev_branch.yaml

feat: change "dev" tag to be "latest" for images

---

README.md

docs: Update images, text and links

---

db/go/20201115133046_update_cvat_env_vars.go
db/go/20210107094725_update_cvat_workspace.go

fix: wrong file for migration rollback

---

db/go/db.go

feat: Evaluate node pool label in Workflow Templates

---

pkg/workflow_execution.go
pkg/workspace_types.go

fix: workspace uid was name and not uid and namespace was not replaced

---

pkg/workflow_template.go

Fixes onepanelio/core#852
**Checklist**
Required

fix: issue where workflow template version did not ignore archived template

---

pkg/workflow_template.go

Fixes onepanelio/core#854
**Checklist**
Required

feat: Allow default for nodepool option

---

README.md

chore: Fix LFAI badge

---

db/go/20200605090509_add_pytorch_workflow_template.go
db/go/20201221194344_pytorch_update.go
db/go/20210118175809_update_node_pool_label.go
db/go/20210129094725_update_cvat_workspace.go
db/go/20210129142057_update_jupyter_workspace.go
db/go/20210129152427_update_vscode_template.go
db/go/db.go
db/yaml/workflows/hyperparameter-tuning/20210118175809.yaml
db/yaml/workflows/maskrcnn-training/20210118175809.yaml
db/yaml/workflows/pytorch-mnist-training/20210118175809.yaml
db/yaml/workflows/tensorflow-mnist-training/20210118175809.yaml
db/yaml/workflows/tf-object-detection-training/20210118175809.yaml
db/yaml/workspaces/cvat/20210129134326.yaml
db/yaml/workspaces/jupyterlab/20210129142057.yaml
db/yaml/workspaces/vscode/20210129152427.yaml

feat: Update all templates for dynamic node labels and new file syncing

---

db/yaml/workflows/maskrcnn-training/20210118175809.yaml

fix: Fix Workflow Template comment

---

db/yaml/workspaces/cvat/20210129134326.yaml
db/yaml/workspaces/jupyterlab/20210129142057.yaml
db/yaml/workspaces/vscode/20210129152427.yaml

chore: Use v0.18.0 for FileSyncer

---

main.go

fix: db not reconnecting

---

db/yaml/workspaces/jupyterlab/20210129142057.yaml
db/yaml/workspaces/vscode/20210129152427.yaml
pkg/workspace.go

fix: Add ONEPANEL_MAIN_CONTAINER env var to all Workspaces

---

db/go/20210224180017_update_workspace_templates.go
db/go/db.go
db/yaml/workspaces/cvat/20210224180017.yaml
db/yaml/workspaces/jupyterlab/20210224180017.yaml
db/yaml/workspaces/vscode/20210224180017.yaml

In combination with https://github.com/onepanelio/core-ui/pull/265
**Checklist**
Required

feat: Update workspace templates

---

pkg/workflow_execution.go
pkg/workspace_template.go

feat: Add labels for better policy management

---

pkg/workflow_execution.go
pkg/workflow_execution_types.go

fix: incorrectly formatted label for workspaces

---

pkg/secret.go

Fixes onepanelio/core#898
**Checklist**
Required

fix:  add error detection when environment variable is too long

---

pkg/workflow_execution.go

**What this PR does**: 
This fixes stability issue with pns executor when using microk8s which doesn't use docker as executor anymore. It is recommended to use empty dir for argo https://argoproj.github.io/argo-workflows/empty-dir/
Required

fix: fixes stability issue with pns executor

---

CONTRIBUTING.md

Added windows specific sections as the commands are slightly different - windows does not have $PWD, but %CD% works.
Also removed minikube section as that is no longer recommended.
**Checklist**
Required

fix: windows sections of contribution guide

---

CONTRIBUTING.md

fix: bash missing character in contributing guide

---

db/go/20210329194731_conditional_remove_hyperparam_tuning.go

fix: bug with remove hyperparam tuning migration

---

db/yaml/workspaces/jupyterlab/20210323175655.yaml

fix: wrong onepanel/dl version

---

pkg/workspace.go

fix: don't use port 80 for host port

---

cmd/gen-release-md/gen-release-md.go

fix: updated repo in generate release notes as the name has changed

---

db/go/20210414165510_add_deep_learning_desktop_workspace.go
db/go/db.go
db/go/util.go
db/yaml/workspaces/vnc/20210414165510.yaml

feat: added deep learning desktop workspace

---

README.md

Add feature highlights video
**Checklist**
Required

chore: Add feature highlights video

---

pkg/workspace.go

fix: use in-cluster url for ONEPANEL_API_URL

---

server/auth/auth.go

feat: auth updates

---

db/go/20210719190719_update_filesyncer.go
db/go/db.go
db/yaml/workspaces/cvat/20210719190719.yaml
db/yaml/workspaces/jupyterlab/20210719190719.yaml
db/yaml/workspaces/vnc/20210719190719.yaml
db/yaml/workspaces/vscode/20210719190719.yaml

feat: added migrations to update filesyncer to version 1.0.0

---

db/go/20210719190719_update_filesyncer.go
pkg/workflow_execution.go

fix: s3 not listing files in file browser

---

server/auth/auth.go

Fixes onepanelio/core#935
**Checklist**
Required

fix: issue where wrong namespace was parsed in certain cases

---

pkg/workflow_execution.go

fix: workflow volumes don't delete on failed workflow

---

README.md

feat: remove enterprise support link

---

README.md

fix: remove slack link
